### PR TITLE
C# 6 features/clean up

### PR DESCRIPTION
**Pull request by ArcticEcho**
To summarise, I've:

 * Used certain features (namely, string interpolation and expression-bodied properties/methods) of C# 6.0 where I feel it brings an improvement (to readability).

 * Removed `ChatbotAction`'s `GetRegexMatchingPattern` and `GetRegexMatchingObject` methods, as I feel they are redundant and can be optimised by using a single new property (`RegexMatchingObject `) which returns a compiled Regex object instead.

 * Removed unused `using` directives.

 * Reorganised all command/trigger classes' members in the following order (as there previously wasn't any order, that I'm aware of anyway): private fields, public properties (sub-ordered alphabetically) and then public methods.

 * Changed all command/trigger methods to properties (besides `RunAction`) and removed the prefix "Get" (I'm still not sure why we were using methods to return simple strings in the first place).

### CODE REVIEW

**Comment by gunr2171** [comment]
Oh, just something I thought of, I compile this with mono on Linux, so hopefully that works.

I'll test that later, still afk

**Comment by ArcticEcho** [comment]
Well the Jenkins build seems to have gone fine.

**Comment by gunr2171** [comment]
Jenkins only builds the main chat bot.

**Comment by ArcticEcho** [comment]
I do not understand oh wise one. Are we not talking about the main bot, since this PR is for the main bot?

**Comment by gunr2171** [comment]
Jenkins build checks closey, not this repository. I'm still out of town, so when I get back I'll see what happens with mono and c# 6.

**Comment by gunr2171** [comment]
God damn it, I'm commenting on the wrong repo. Ignore everything I've said.

**Comment by ArcticEcho** [comment]
Lol, that explains it.

**Pull request merged**
