### PR TITLE
Submodules

### PR DESCRIPTION
**Pull request by ArcticEcho**
This should move TheCommonLibrary, SOCVR.Net & ChatExchange.Net to submodules (I've had to slightly alter a couple of lines in the `RoomManager` class for it to work with the older version of the chat lib).

### CODE REVIEW

**Comment by gunr2171** [comment]
Hum, so here's what I was afraid of. I'm getting a bunch of "I can't find the nuget package" errors from the CE.Net and SOCVR.Net libraries. I'll see if I can do something about it....

**Comment by gunr2171** [comment]
Hum, I made some changes to master, so you'll need to update (sorry about that).

**Comment by ArcticEcho** [comment]
Huh, that's weird. Sure, np.

**Comment by ArcticEcho** [comment]
I've updated CE.Net (to hopefully resolve some dependency issues), so I think it'll be best to just scrap this branch and start again.

**Comment by gunr2171** [comment]
2896c4180ba0aeedcdb31bc70a02120804b58d49

Drops mic.

**Pull request closed without merging**
