### PR TITLE
Use SOCVR.Net package

### LINKED ISSUE #79: Poke to see if users are still alive after starting a session for so long.
The bot could poke a user after a while of starting in case they've forgotten.

> Hey @gunr2171, you haven't reported in an hour. Did you only forget or should we send a search team?

From #77

### PR DESCRIPTION
**Pull request by ArcticEcho**
This branch uses the new SOCVR.Net NuGet package which actively monitors registered users' CV review activity. The `starting` command has been made redundant, but I haven't removed it.

<strike>I haven't been able to debug any DB related operations (since I don't have the DB), so I can't verify they work</strike> (I've simply moved the necessary DB accessor code from the chat commands/triggers to the new `UserWatcher` events).

(In addition, this will most likely close #79.)

### CODE REVIEW

**Comment by ArcticEcho** [comment]
Also, [these lines](https://github.com/SO-Close-Vote-Reviewers/SOCVR-Chatbot/blob/socvr.net-update/CVChatbot/CVChatbot.Bot/UserWatcherManager.cs#L101-L104) may need calibrating.

**Comment by gunr2171** [comment]
test this please

**Comment by gunr2171** [comment]
test this please

**Comment by gunr2171** [comment]
test this please

**Comment by gunr2171** [comment]
retest this please

**Comment by ArcticEcho** [comment]
Development for v2 has now been moved to the [`v2-dev` branch](https://github.com/SO-Close-Vote-Reviewers/SOCVR-Chatbot/tree/v2-dev).

**Comment by gunr2171** [comment]
Just don't delete this branch. There is still important code saved here that we will be referencing for v2.

**Pull request closed without merging**
